[build]
  publish = "public"
  command = ""

[dev]
  command = "npm run dev"
  port = 8888

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

